export default {
  ic_back : require('../assets/images/images/ic-back.png'),
  ic_bell: require('../assets/images/images/ic-bell.png'),
  ic_history:require('../assets/images/images/ic-history.png'),
  ic_chamcong:require('../assets/images/images/ic-chamcong.png'),
  ic_time_table :require('../assets/images/images/ic_time_table.png'),
  ic_conpany :require('../assets/images/images/ic-company.png'),
  ic_user :require('../assets/images/images/ic-user.png'),
  ic_lich :require('../assets/images/images/ic-lich.png'),
  ic_down :require('../assets/images/images/ic-down.png'),
  ic_checkin :require('../assets/images/images/ic-checkin.png'),
  ic_checkout :require('../assets/images/images/ic-checkout.png'),
  ic_arrowRight :require('../assets/images/images/icArrowRightBlack.png'),
  ic_shifts :require('../assets/images/images/ic-shifts.png'),
  ic_employee :require('../assets/images/images/ic-employee.png'),
  ic_location :require('../assets/images/images/icon-location.png'),
  ic_phongban :require('../assets/images/images/phongban.png'),
  ic_pay :require('../assets/images/images/ic-pay.png'),
  ic_radioFalse :require('../assets/images/images/radioFalse.png'),
  ic_radioTrue :require('../assets/images/images/radioTrue.png'),
  ic_faceRecognition :require('../assets/images/images/ic_nhandienkhuonmat.jpg'),
  ic_bottomtab :require('../assets/images/images/ic_bottomtab.png'),
  ic_search :require('../assets/images/images/ic-search.png'),
  ic_camera :require('../assets/images/images/ic-camera.png'),
  ic_library :require('../assets/images/images/icon-library.png'),
  ic_refresh :require('../assets/images/images/ic-refresh.png'),
  img_noInternet :require('../assets/images/images/img-nointernet.png'),
}
